/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Region as PrismaRegion,
  PovertyData as PrismaPovertyData,
} from "@prisma/client";

export class RegionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.RegionCountArgs, "select">): Promise<number> {
    return this.prisma.region.count(args);
  }

  async regions<T extends Prisma.RegionFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.RegionFindManyArgs>
  ): Promise<PrismaRegion[]> {
    return this.prisma.region.findMany<Prisma.RegionFindManyArgs>(args);
  }
  async region<T extends Prisma.RegionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.RegionFindUniqueArgs>
  ): Promise<PrismaRegion | null> {
    return this.prisma.region.findUnique(args);
  }
  async createRegion<T extends Prisma.RegionCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.RegionCreateArgs>
  ): Promise<PrismaRegion> {
    return this.prisma.region.create<T>(args);
  }
  async updateRegion<T extends Prisma.RegionUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.RegionUpdateArgs>
  ): Promise<PrismaRegion> {
    return this.prisma.region.update<T>(args);
  }
  async deleteRegion<T extends Prisma.RegionDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.RegionDeleteArgs>
  ): Promise<PrismaRegion> {
    return this.prisma.region.delete(args);
  }

  async findPovertyDataItems(
    parentId: string,
    args: Prisma.PovertyDataFindManyArgs
  ): Promise<PrismaPovertyData[]> {
    return this.prisma.region
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .povertyDataItems(args);
  }
}
