/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PovertyDataService } from "../povertyData.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PovertyDataCreateInput } from "./PovertyDataCreateInput";
import { PovertyData } from "./PovertyData";
import { PovertyDataFindManyArgs } from "./PovertyDataFindManyArgs";
import { PovertyDataWhereUniqueInput } from "./PovertyDataWhereUniqueInput";
import { PovertyDataUpdateInput } from "./PovertyDataUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PovertyDataControllerBase {
  constructor(
    protected readonly service: PovertyDataService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PovertyData })
  @nestAccessControl.UseRoles({
    resource: "PovertyData",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPovertyData(
    @common.Body() data: PovertyDataCreateInput
  ): Promise<PovertyData> {
    return await this.service.createPovertyData({
      data: {
        ...data,

        region: data.region
          ? {
              connect: data.region,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        population: true,
        povertyRate: true,

        region: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        year: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PovertyData] })
  @ApiNestedQuery(PovertyDataFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PovertyData",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async povertyDataItems(
    @common.Req() request: Request
  ): Promise<PovertyData[]> {
    const args = plainToClass(PovertyDataFindManyArgs, request.query);
    return this.service.povertyDataItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        population: true,
        povertyRate: true,

        region: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        year: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PovertyData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PovertyData",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async povertyData(
    @common.Param() params: PovertyDataWhereUniqueInput
  ): Promise<PovertyData | null> {
    const result = await this.service.povertyData({
      where: params,
      select: {
        createdAt: true,
        id: true,
        population: true,
        povertyRate: true,

        region: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        year: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PovertyData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PovertyData",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePovertyData(
    @common.Param() params: PovertyDataWhereUniqueInput,
    @common.Body() data: PovertyDataUpdateInput
  ): Promise<PovertyData | null> {
    try {
      return await this.service.updatePovertyData({
        where: params,
        data: {
          ...data,

          region: data.region
            ? {
                connect: data.region,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          population: true,
          povertyRate: true,

          region: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          year: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PovertyData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PovertyData",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePovertyData(
    @common.Param() params: PovertyDataWhereUniqueInput
  ): Promise<PovertyData | null> {
    try {
      return await this.service.deletePovertyData({
        where: params,
        select: {
          createdAt: true,
          id: true,
          population: true,
          povertyRate: true,

          region: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          year: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
